// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.4
// source: colorapi/service.proto

package colorapi

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ColorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColorResp *Color `protobuf:"bytes,1,opt,name=color_resp,json=colorResp,proto3" json:"color_resp,omitempty"`
}

func (x *ColorResponse) Reset() {
	*x = ColorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colorapi_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorResponse) ProtoMessage() {}

func (x *ColorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colorapi_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorResponse.ProtoReflect.Descriptor instead.
func (*ColorResponse) Descriptor() ([]byte, []int) {
	return file_colorapi_service_proto_rawDescGZIP(), []int{0}
}

func (x *ColorResponse) GetColorResp() *Color {
	if x != nil {
		return x.ColorResp
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colorapi_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_colorapi_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_colorapi_service_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Color struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hex  string `protobuf:"bytes,2,opt,name=hex,proto3" json:"hex,omitempty"`
	RGB  uint32 `protobuf:"fixed32,3,opt,name=RGB,proto3" json:"RGB,omitempty"`
}

func (x *Color) Reset() {
	*x = Color{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colorapi_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_colorapi_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_colorapi_service_proto_rawDescGZIP(), []int{2}
}

func (x *Color) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Color) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

func (x *Color) GetRGB() uint32 {
	if x != nil {
		return x.RGB
	}
	return 0
}

type StartIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *StartIndex) Reset() {
	*x = StartIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colorapi_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIndex) ProtoMessage() {}

func (x *StartIndex) ProtoReflect() protoreflect.Message {
	mi := &file_colorapi_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIndex.ProtoReflect.Descriptor instead.
func (*StartIndex) Descriptor() ([]byte, []int) {
	return file_colorapi_service_proto_rawDescGZIP(), []int{3}
}

func (x *StartIndex) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_colorapi_service_proto protoreflect.FileDescriptor

var file_colorapi_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x61,
	0x70, 0x69, 0x22, 0x3f, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x09, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x68, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x47, 0x42, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x03, 0x52, 0x47, 0x42, 0x22, 0x22, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x32, 0x88, 0x01, 0x0a, 0x06,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x12, 0x42, 0x0a, 0x0d, 0x50, 0x69, 0x63, 0x6b, 0x41, 0x6c,
	0x6c, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x17, 0x2e,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x14, 0x41, 0x64,
	0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x48, 0x65, 0x78, 0x4f, 0x72, 0x52,
	0x67, 0x62, 0x12, 0x0f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x1a, 0x0f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x69, 0x6b, 0x6f, 0x6e, 0x30, 0x30, 0x31, 0x2f, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_colorapi_service_proto_rawDescOnce sync.Once
	file_colorapi_service_proto_rawDescData = file_colorapi_service_proto_rawDesc
)

func file_colorapi_service_proto_rawDescGZIP() []byte {
	file_colorapi_service_proto_rawDescOnce.Do(func() {
		file_colorapi_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_colorapi_service_proto_rawDescData)
	})
	return file_colorapi_service_proto_rawDescData
}

var file_colorapi_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_colorapi_service_proto_goTypes = []interface{}{
	(*ColorResponse)(nil), // 0: colorapi.ColorResponse
	(*Reply)(nil),         // 1: colorapi.Reply
	(*Color)(nil),         // 2: colorapi.Color
	(*StartIndex)(nil),    // 3: colorapi.StartIndex
}
var file_colorapi_service_proto_depIdxs = []int32{
	2, // 0: colorapi.ColorResponse.color_resp:type_name -> colorapi.Color
	3, // 1: colorapi.Colors.PickAllColors:input_type -> colorapi.StartIndex
	2, // 2: colorapi.Colors.AddColorFromHexOrRgb:input_type -> colorapi.Color
	0, // 3: colorapi.Colors.PickAllColors:output_type -> colorapi.ColorResponse
	1, // 4: colorapi.Colors.AddColorFromHexOrRgb:output_type -> colorapi.Reply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_colorapi_service_proto_init() }
func file_colorapi_service_proto_init() {
	if File_colorapi_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_colorapi_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_colorapi_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_colorapi_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Color); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_colorapi_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_colorapi_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_colorapi_service_proto_goTypes,
		DependencyIndexes: file_colorapi_service_proto_depIdxs,
		MessageInfos:      file_colorapi_service_proto_msgTypes,
	}.Build()
	File_colorapi_service_proto = out.File
	file_colorapi_service_proto_rawDesc = nil
	file_colorapi_service_proto_goTypes = nil
	file_colorapi_service_proto_depIdxs = nil
}
